services:
  gradle-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: gradle-app
    working_dir: /app
    command: ["./gradlew", "appRun", "--no-daemon"]
