version: "3"
services:
  gradle-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: burtonjong/ensf400fp:latest
    ports:
      - "8080:8080"
    container_name: gradle-app
    working_dir: /app
    command: ["./gradlew", "appRun", "--no-daemon"]
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /workspaces/ensf400-lab9-jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock