name: Docker Push to Docker Hub

on:
  push:
    branches:
      - main  # Only push on changes to main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git Commit SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t burtonjong/ensf400fp:${{ env.GIT_SHA }} .
          docker tag burtonjong/ensf400fp:${{ env.GIT_SHA }} burtonjong/ensf400fp:latest

      - name: Push Docker Image
        run: |
          docker push burtonjong/ensf400fp:${{ env.GIT_SHA }}
          docker push burtonjong/ensf400fp:latest
